### PR TITLE
Master

### PR DESCRIPTION
**Pull request by fabanc**
The code for curve interpolation had specific bugs that were identified but troublesome to solve. This code change contains:
1. Competely new code for dealing with curve interpolation. Easier to understand, it simply takes the input segment and turn it into an horizontal directix in order to solve the parabola equation. The input points, and parabola ends are moved accordingly.
2. Inconsistencies when storing the input geometries. The geometries store didn't not reflect the changes introduced by the scale factors. Those inconsistencies had an impact on the curve interpolation.
3. Introduction of exceptions specific to the parabola computation. Some of those exception can be impacted by the scale factor used, therefore this tolerance has been exposed as a parameter that the user can modify. Best practice with that parameter and dealing with those exception has been documented.
4. Modified unit test to reflex changes in #2.

### CODE REVIEW

**Comment by fabanc** [comment]
Any issue with the pull request?

**Comment by maxvoxel8** [comment]
I'm not really maintaining this package anymore. I'd be happy to transfer ownership to you on pypi if you're interested.

**Comment by fabanc** [comment]
I would be happy to continue on improving it. Does it mean you are going to add me as a collaborator on this github project or do you want me to host that on my own github repo?

**Comment by fabanc** [comment]
By the way my Pypi user name is fabanc as well.

**Comment by jminardi** [comment]
Hi @fabanc I added you as a collaborator. @maxvoxel8 Can transfer ownership of the pypi repo

**Comment by maxvoxel8** [comment]
@fabanc I added you as owner on pypi.

**Comment by fabanc** [comment]
Perfect. Thanks!


2017-04-05 13:45 GMT-04:00 Max Eskin <notifications@github.com>:

**Pull request merged**
